# Site settings
title: Han Junhui
email: contactme@hanjunhui.com
description: > # this means to ignore newlines until "baseurl:"
  独立之精神，自由之思想！
baseurl: "/p-blog" # the subpath of your site, e.g. /blog/
url: "jsph06.github.io" # the base hostname & protocol for your site
twitter_username: jsph_06
github_username:  jsph06

# Build settings
markdown: kramdown
